# USANDO A EXTENSÃO DO PYTHON PARA COMENTÁRIOS (Comment Anchors

# TODO - Trecho para fazer
# NOTE - NOTA SOBRE O TRECHO DE CÓDIGO
# FIXME - CORRIGIR O TRECHO DE CÓDIGO
# REVIEW - REVISAR O TRECHO DE CÓDIGO 
# ANCHOR - MARCAR TRECHO DE CÓDIGO
# SECTION - INICIA UMA SEÇÃO SEÇÃO DE UM TRECHO DE CÓDIGO
# !SECTION - TERMINA UMA SEÇÃO SEÇÃO DE UM TRECHO DE CÓDIGO


# Comentários em Python
"""

Comentário de 
multiplas linhas.

"""